### ISSUE TITLE
Inclusion of check to detect existing Quickfix window

### ISSUE THREAD

**Issue by achakravarti** [vshih/vim-make#1]
Hi Victor!

First of all, I'd like to say that Make.vim is a real life-saver -- many thanks for the effort that you put into it!
In my Vim configuration, I like to open the editor with a Quickfix window, and keep it open by default. When running Make.vim, this Quickfix window is closed, changing the pane layout in the editor. I tweaked this for my situation by removing the `cclose` statements in Make.vim.

I was just wondering -- would it be possible to include a check to detect an existing Quickfix window and write to it instead of closing it and opening a new instance?

Once again, many thanks! :+1:

**Comment by vshih** [comment]
Hey thanks for the comments!  I'll look into this this weekend.

**Comment by vshih** [comment]
@achakravarti take a look at the feature/quickfix-config branch.

**Comment by achakravarti** [comment]
@vshih works like a charm! I copied the plugin from the `feature/quickfix-config` branch, and `let g:Make_quickfix_always_open=1` in my `.vimrc`, and the existing quickfix window is retained.

Many thanks for the update! :100:
